SolarPerformanceInsight/solarperformanceinsight

- .codecov.yml
- requirements-test.txt
- solarperformanceinsight_api/__init__.py
- solarperformanceinsight_api/auth.py
- solarperformanceinsight_api/main.py
- solarperformanceinsight_api/models.py
- solarperformanceinsight_api/routers/__init__.py
- solarperformanceinsight_api/routers/plants.py
- solarperformanceinsight_api/tests/test_app.py
- solarperformanceinsight_api/tests/test_models.py
test hypothesis and see if codecov shows up
> add more system models

- .github/workflows/javascript.yml
- .github/workflows/python.yml
> adjust workflows to always test both python and javascript

- dashboard/package-lock.json
- dashboard/package.json
- dashboard/src/components/TrackingParameters.vue
- dashboard/src/main.ts
- dashboard/src/router/index.ts
- dashboard/src/types/validation/Validator.ts
- dashboard/src/validator.d.ts
- dashboard/vue.config.js
Adds a class that uses the OpenAPI schema to validate objects on user input. Validation is performed using the Ajv library. The class also allows access to the underlying JSON of the spec for use printing descriptions etc.
As a proof of concept, this is implemented for tracking parameters.
> Validate objects based on openapi schema

- .github/workflows/database.yml
- .gitignore
- .pre-commit-config.yaml
- db/README.md
- db/migrations/20201130184500_create_users.sql
- db/migrations/20201130190000_create_users_table.sql
- db/migrations/20201130190100_create_systems_table.sql
- db/schema.sql
- db/test-requirements.txt
- db/tests/conftest.py
- db/tests/test_systems.py
- db/tests/test_users.py
Including users and systems tables.
> Start adding db tables

- api/solarperformanceinsight_api/models.py
- api/solarperformanceinsight_api/routers/systems.py
- api/solarperformanceinsight_api/tests/test_app.py
- api/solarperformanceinsight_api/tests/test_models.py
to play nicely with mypy and add a specific system example to OpenAPI. 
Will rebase on #27 once that's in
> Update model fields

- dashboard/.eslintrc.js
- dashboard/.prettierrc.js
- dashboard/src/App.vue
- dashboard/src/components/Array.vue
- dashboard/src/components/FileUpload.vue
- dashboard/src/components/Inverter.vue
- dashboard/src/components/InverterParameters.vue
- dashboard/src/components/ModuleParameters.vue
- dashboard/src/components/System.vue
- dashboard/src/components/TemperatureParameters.vue
- dashboard/src/components/TrackingParameters.vue
- dashboard/src/views/Model.vue
- dashboard/src/views/Systems.vue
Adjusts prettier config to fix weird html line breaks noted in #19. Just includes results of lint fixes. Should be merge between #30 and #31.
> Adjust prettier config

- api/solarperformanceinsight_api/conftest.py
- api/solarperformanceinsight_api/main.py
- api/solarperformanceinsight_api/models.py
- api/solarperformanceinsight_api/routers/user.py
- api/solarperformanceinsight_api/storage.py
- api/solarperformanceinsight_api/tests/test_app.py
- api/solarperformanceinsight_api/tests/test_storage.py
and automatically create users in the db when appropriate
> add a simple user endpoint

- api/solarperformanceinsight_api/routers/systems.py
- api/solarperformanceinsight_api/routers/tests/test_systems.py
- api/solarperformanceinsight_api/tests/test_app.py
without saving the system. Does not check a ModelChain object yet in the interest of keeping PRs small
> add a /systems/check endpoint to validate json

- dashboard/src/components/model/ModuleParameters.vue
- dashboard/tests/unit/test_model_components.spec.ts
Mounts and checks that all of the expected fields are represented in components so we don't leave out fields.
> Add basic model component tests

- .github/workflows/python.yml
- api/solarperformanceinsight_api/conftest.py
- api/solarperformanceinsight_api/main.py
- api/solarperformanceinsight_api/models.py
- api/solarperformanceinsight_api/routers/systems.py
- api/solarperformanceinsight_api/routers/tests/test_systems.py
- api/solarperformanceinsight_api/tests/test_app.py
but keep schemathesis as it may still find errors that manual
tests miss
> reduce flakiness of tests by testing all /systems endpoints

- api/solarperformanceinsight_api/routers/jobs.py
- api/solarperformanceinsight_api/routers/tests/test_jobs.py
> handle None in jobs._get_return_type

- dashboard/src/utils/schemaIndexing.ts
- dashboard/tests/unit/utils/test_schemaIndexing.spec.ts
Adds a small utility function for indexing into a System spec from a loc/schema path.
> Add dashboard utility indexer

- api/solarperformanceinsight_api/compute.py
- api/solarperformanceinsight_api/tests/test_compute.py
- api/solarperformanceinsight_api/tests/test_utils.py
- api/solarperformanceinsight_api/utils.py
closes #108. Also makes convert_to_arrow work more broadly without
assuming much about the dataframe structure
> use month names in summary index

- dashboard/src/components/jobs/CSVMapper.vue
- dashboard/src/components/jobs/CSVUpload.vue
- dashboard/src/components/jobs/FieldMapper.vue
- dashboard/src/components/jobs/SingleMapping.vue
- dashboard/src/utils/mapToCSV.ts
- dashboard/src/utils/powerConversion.ts
- dashboard/tests/unit/jobs/test_csvmapper.spec.ts
- dashboard/tests/unit/jobs/test_csvupload.spec.ts
- dashboard/tests/unit/jobs/test_fieldmapper.spec.ts
- dashboard/tests/unit/utils/test_maptocsv.spec.ts
- dashboard/tests/unit/utils/test_power_conversion.spec.ts
> Allow users to define performance units

- dashboard/src/components/jobs/data/SummaryTable.vue
- dashboard/src/components/jobs/data/TimeseriesResultsTable.vue
- dashboard/src/components/jobs/parameters/DatetimeField.vue
- dashboard/src/utils/displayNames.ts
- dashboard/src/utils/units.ts
> Handle 2a results correctly

- api/solarperformanceinsight_api/compute.py
occurs when poa_ref = 0 so poa_factor = inf, but pac_ref is also zero,
so set the adjusted pac to 0 instead of nan
> make inf * 0 = 0 for weather adjusted performance

- dashboard/src/components/jobs/CSVMapper.vue
- dashboard/src/components/jobs/CSVUpload.vue
- dashboard/src/components/jobs/FieldMapper.vue
- dashboard/src/components/jobs/SingleMapping.vue
- dashboard/src/components/jobs/data/CSVPreview.vue
- dashboard/src/utils/mapToCSV.ts
- dashboard/src/utils/parseCSV.ts
- dashboard/tests/unit/jobs/test_csvmapper.spec.ts
- dashboard/tests/unit/jobs/test_csvupload.spec.ts
- dashboard/tests/unit/jobs/test_fieldmapper.spec.ts
- dashboard/tests/unit/utils/test_maptocsv.spec.ts
- dashboard/tests/unit/utils/test_parsecsv.spec.ts
Allows users to set the header row to 0, and creates some stub headers like "Column 1, Column 2" etc.
closes #158
> Allow no header CSV

- api/solarperformanceinsight_api/compute.py
- api/solarperformanceinsight_api/tests/test_compute.py
> fix temperature loss coefficient

- dashboard/src/components/jobs/CSVUpload.vue
- dashboard/src/components/jobs/CustomResultPlots.vue
- dashboard/src/components/jobs/JobHandler.vue
- dashboard/src/components/jobs/JobResults.vue
- dashboard/src/components/jobs/data/MultiTimeSeries.vue
- dashboard/src/components/jobs/data/TimeseriesResultsTable.vue
- dashboard/src/components/jobs/parameters/DataParamHandler.vue
- dashboard/src/components/jobs/parameters/DataParams.vue
- dashboard/src/components/jobs/parameters/DatetimeField.vue
- dashboard/src/components/jobs/parameters/JobParams.vue
- dashboard/src/components/jobs/parameters/TimeParameters.vue
- dashboard/tests/unit/jobs/test_csvupload.spec.ts
- dashboard/tests/unit/jobs/test_jobhandler.spec.ts
PR for handling smaller issues raised in #180. 
closes #180, other items in follow up issues.
> 2a feedback updates

- dashboard/src/components/Browser.vue
- dashboard/src/components/ModelField.vue
- dashboard/src/components/jobs/CSVUpload.vue
- dashboard/src/components/jobs/CustomResultPlots.vue
- dashboard/src/components/jobs/FieldMapper.vue
- dashboard/src/components/jobs/JobResults.vue
- dashboard/src/components/jobs/parameters/DataParamHandler.vue
- dashboard/src/components/jobs/parameters/DataParams.vue
- dashboard/src/components/jobs/parameters/TimeParameters.vue
- dashboard/src/components/model/InverterParameters.vue
- dashboard/src/components/model/ModuleParameters.vue
- dashboard/src/components/model/System.vue
- dashboard/src/views/Systems.vue
- dashboard/tests/unit/jobs/test_csvupload.spec.ts
- dashboard/tests/unit/jobs/test_fieldmapper.spec.ts
- dashboard/tests/unit/test_model_components.spec.ts
closes #198 
Most bugs are handled thoroughly, but the labelling for effective irradiance here is just a bandaid. I'm checking for the "effective_irradiance" variable during the data declaration/mapping process and replacing it with "Effective Irradiance or Plane of Array Global Irradiance". On the results side, I'm leaving everything as "effective irradiance". Does that sound reasonable?
> Minor bugs

- dashboard/src/components/jobs/CSVUpload.vue
- dashboard/src/components/jobs/JobHandler.vue
- dashboard/src/components/jobs/JobResults.vue
- dashboard/src/components/jobs/data/SummaryTable.vue
- dashboard/src/components/jobs/data/TimeseriesResultsTable.vue
- dashboard/src/components/jobs/parameters/CompareJobParams.vue
- dashboard/src/components/jobs/parameters/DataParamHandler.vue
- dashboard/src/components/jobs/parameters/DataParams.vue
- dashboard/src/store/actions.ts
- dashboard/src/utils/units.ts
- dashboard/tests/unit/jobs/test_csvupload.spec.ts
- dashboard/tests/unit/jobs/test_jobparameters.spec.ts
- dashboard/tests/unit/utils/test_display_names.spec.ts
- dashboard/tests/unit/utils/test_unit_conversion.spec.ts
- dashboard/tests/unit/utils/test_units.spec.ts
> Dashboard modeled vs reference usecase
